const AllahName = [
	{
		id: 1,
		nameEng: "Ar-Rahman",
		nameHin: "अर रहमान",
		meaning: "बहुत महेरबान",
	},
	{
		id: 2,
		nameEng: "Ar-Rahim",
		nameHin: "अर रहीम",
		meaning: "निहायत रहम वाला",
	},
	{
		id: 3,
		nameEng: "Al-Malik",
		nameHin: "अल मलिक",
		meaning: "बादशाह",
	},
	{
		id: 4,
		nameEng: "Al-Quddus",
		nameHin: "अल कुद्दुस",
		meaning: "पाक ज़ात",
	},
	{
		id: 5,
		nameEng: "As-Salam",
		nameHin: "अस सलाम",
		meaning: "सलामती वाला",
	},
	{
		id: 6,
		nameEng: "Al-Mu'min",
		nameHin: "अल मु अमिन",
		meaning: "अमन देने वाला",
	},
	{
		id: 7,
		nameEng: "Al-Muhaymin",
		nameHin: "अल मुहयमिन",
		meaning: "निगरानी करने वाला",
	},
	{
		id: 8,
		nameEng: "Al-Aziz",
		nameHin: "अल अज़ीज़",
		meaning: "ग़ालिब",
	},
	{
		id: 9,
		nameEng: "Al-Jabbar",
		nameHin: "अल जब्बार",
		meaning: "नुकसान को पूरा करने वाला",
	},
	{
		id: 10,
		nameEng: "Al-Mutakabbir",
		nameHin: "अल मुतकब्बिर",
		meaning: "बड़ाई वाला",
	},
	{
		id: 11,
		nameEng: "Al-Khaliq",
		nameHin: "अल खालिक",
		meaning: "पैदा करने वाला",
	},
	{
		id: 12,
		nameEng: "Al-Bari",
		nameHin: "अल बारी",
		meaning: "जान डालने वाला",
	},
	{
		id: 13,
		nameEng: "Al-Musawwir",
		nameHin: "अल मुसव्विर",
		meaning: "सूरतें बनाने वाला",
	},
	{
		id: 14,
		nameEng: "Al-Ghaffar",
		nameHin: "अल गफ्फार",
		meaning: "बख्शने वाला",
	},
	{
		id: 15,
		nameEng: "Al-Qahhar",
		nameHin: "अल क़हहार",
		meaning: "सब को अपने काबू में रखने वाला",
	},
	{
		id: 16,
		nameEng: "Al-Wahhab",
		nameHin: "अल वहहाब",
		meaning: "बहुत अता करने वाला",
	},
	{
		id: 17,
		nameEng: "Ar-Razzaq",
		nameHin: "अर रज्जाक",
		meaning: "रिजक देने वाला",
	},
	{
		id: 18,
		nameEng: "Al-Fattah",
		nameHin: "अल फतताह",
		meaning: "खोलने वाला",
	},
	{
		id: 19,
		nameEng: "Al-Alim",
		nameHin: "अल अलीम",
		meaning: "खूब जानने वाला",
	},
	{
		id: 20,
		nameEng: "Al-Qabid",
		nameHin: "अल काबिज़",
		meaning: "नपी तुली रोज़ी देने वाला",
	},
	{
		id: 21,
		nameEng: "Al-Basit",
		nameHin: "अल बासित",
		meaning: "रोज़ी को फराख देने वाला",
	},
	{
		id: 22,
		nameEng: "Al-Khafidh",
		nameHin: "अल खाफिज़",
		meaning: "पस्त करने वाला",
	},
	{
		id: 23,
		nameEng: "Ar-Rafi",
		nameHin: "अर राफी",
		meaning: "बलंद करने वाला",
	},
	{
		id: 24,
		nameEng: "Al-Mu'izz",
		nameHin: "अल मुईज़",
		meaning: "इज्ज़त देने वाला",
	},
	{
		id: 25,
		nameEng: "Al-Mudhill",
		nameHin: "अल मुज़िल",
		meaning: "ज़िल्लत देने वाला",
	},
	{
		id: 26,
		nameEng: "As-Sami",
		nameHin: "अस समी",
		meaning: "सब कुछ सुनने वाला",
	},
	{
		id: 27,
		nameEng: "Al-Basir",
		nameHin: "अल बसीर",
		meaning: "सब कुछ देखने वाला",
	},
	{
		id: 28,
		nameEng: "Al-Hakam",
		nameHin: "अल हकम",
		meaning: "फैसला करने वाला",
	},
	{
		id: 29,
		nameEng: "Al-Adl",
		nameHin: "अल अदल",
		meaning: "अदल करने वाला",
	},
	{
		id: 30,
		nameEng: "Al-Latif",
		nameHin: "अल लतीफ़",
		meaning: "बारीक बीं",
	},
	{
		id: 31,
		nameEng: "Al-Khabir",
		nameHin: "अल खबीर",
		meaning: "सब से बाखबर",
	},
	{
		id: 32,
		nameEng: "Al-Halim",
		nameHin: "अल हलीम",
		meaning: "निहायत बुरदबार",
	},
	{
		id: 33,
		nameEng: "Al-Azim",
		nameHin: "अल अज़ीम",
		meaning: "बुज़ुर्ग",
	},
	{
		id: 34,
		nameEng: "Al-Ghafur",
		nameHin: "अल गफूर",
		meaning: "गुनाहों को बख्शने वाला",
	},
	{
		id: 35,
		nameEng: "Ash-Shakur",
		nameHin: "अश शकूर",
		meaning: "कदरदान",
	},
	{
		id: 36,
		nameEng: "Al-Ali",
		nameHin: "अल अली",
		meaning: "बहुत बुलंद",
	},
	{
		id: 37,
		nameEng: "Al-Kabir",
		nameHin: "अल कबीर",
		meaning: "बहुत बड़ा",
	},
	{
		id: 38,
		nameEng: "Al-Hafiz",
		nameHin: "अल हफीज़",
		meaning: "निगेहबान",
	},
	{
		id: 39,
		nameEng: "Al-Muqit",
		nameHin: "अल मुकीत",
		meaning: "सब को रोज़ी व तवानाई देने वाला",
	},
	{
		id: 40,
		nameEng: "Al-Hasib",
		nameHin: "अल हसीब",
		meaning: "काफी",
	},
	{
		id: 41,
		nameEng: "Al-Jalil",
		nameHin: "अल जलील",
		meaning: "बुज़ुर्ग",
	},
	{
		id: 42,
		nameEng: "Al-Karim",
		nameHin: "अल करीम",
		meaning: "बेइंतिहा करम करने वाला",
	},
	{
		id: 43,
		nameEng: "Ar-Raqib",
		nameHin: "अर रक़ीब",
		meaning: "निगेहबान",
	},
	{
		id: 44,
		nameEng: "Al-Mujib",
		nameHin: "अल मुजीब",
		meaning: "दुआएं सुनने और कुबूल करने वाला",
	},
	{
		id: 45,
		nameEng: "Al-Wasi",
		nameHin: "अल वासिऊ",
		meaning: "कुशादगी देने वाला",
	},
	{
		id: 46,
		nameEng: "Al-Hakim",
		nameHin: "अल हकीम",
		meaning: "हिकमत वाला",
	},
	{
		id: 47,
		nameEng: "Al-Wadud",
		nameHin: "अल वदूद",
		meaning: "मुहब्बत करने वाला, दोस्त",
	},
	{
		id: 48,
		nameEng: "Al-Majid",
		nameHin: "अल मजीद",
		meaning: "बड़ी शान वाला",
	},
	{
		id: 49,
		nameEng: "Al-Ba'ith",
		nameHin: "अल बाईस",
		meaning: "उठाने वाला",
	},
	{
		id: 50,
		nameEng: "Ash-Shahid",
		nameHin: "अश शहीद",
		meaning: "हाज़िर",
	},
	{
		id: 51,
		nameEng: "Al-Haqq",
		nameHin: "अल हक",
		meaning: "सच्चा मालिक",
	},
	{
		id: 52,
		nameEng: "Al-Wakil",
		nameHin: "अल वकील",
		meaning: "काम बनाने वाला",
	},
	{
		id: 53,
		nameEng: "Al-Qawi",
		nameHin: "अल कवी",
		meaning: "शक्तिशाली",
	},
	{
		id: 54,
		nameEng: "Al-Matin",
		nameHin: "अल मतीन",
		meaning: "कुव्वत वाला",
	},
	{
		id: 55,
		nameEng: "Al-Wali",
		nameHin: "अल वली",
		meaning: "हिमायत करने वाला",
	},
	{
		id: 56,
		nameEng: "Al-Hamid",
		nameHin: "अल हमीद",
		meaning: "खूबियों वाला",
	},
	{
		id: 57,
		nameEng: "Al-Muhsi",
		nameHin: "अल मुह्सी",
		meaning: "गिनने वाला",
	},
	{
		id: 58,
		nameEng: "Al-Mubdi",
		nameHin: "अल मुब्दी",
		meaning: "पहली बार पैदा करने वाला",
	},
	{
		id: 59,
		nameEng: "Al-Mu'id",
		nameHin: "अल मुईद",
		meaning: "दोबारा पैदा करने वाला",
	},
	{
		id: 60,
		nameEng: "Al-Muhyi",
		nameHin: "अल मुहयी",
		meaning: "जिंदा करने वाला",
	},
	{
		id: 61,
		nameEng: "Al-Mumit",
		nameHin: "अल मुमीत",
		meaning: "मारने वाला",
	},
	{
		id: 62,
		nameEng: "Al-Hayy",
		nameHin: "अल हय्युल",
		meaning: "जिंदा",
	},
	{
		id: 63,
		nameEng: "Al-Qayyum",
		nameHin: "अल कय्यूम",
		meaning: "सब को कायम रखने और निभाने वाला",
	},
	{
		id: 64,
		nameEng: "Al-Wajid",
		nameHin: "अल वाजिद",
		meaning: "हर चीज़ को पाने वाला",
	},
	{
		id: 65,
		nameEng: "Al-Majid",
		nameHin: "अल माजिद",
		meaning: "बुज़ुर्गी और बड़ाई वाला",
	},
	{
		id: 66,
		nameEng: "Al-Wahid",
		nameHin: "अल वाहिद",
		meaning: "एक",
	},
	{
		id: 67,
		nameEng: "Al-Ahad",
		nameHin: "अल अहद",
		meaning: "अकेला",
	},
	{
		id: 68,
		nameEng: "As-Samad",
		nameHin: "अस समद",
		meaning: "बे नियाज़",
	},
	{
		id: 69,
		nameEng: "Al-Qadir",
		nameHin: "अल कादिर",
		meaning: "कुदरत रखने वाला",
	},
	{
		id: 70,
		nameEng: "Al-Muqtadir",
		nameHin: "अल मुक्तदिर",
		meaning: "पूरी कुदरत रखने वाला",
	},
	{
		id: 71,
		nameEng: "Al-Muqaddim",
		nameHin: "अल मुक़द्दम",
		meaning: "आगे करने वाला",
	},
	{
		id: 72,
		nameEng: "Al-Muakhkhir",
		nameHin: "अल मुअख्खर",
		meaning: "पीछे और बाद में रखने वाला",
	},
	{
		id: 73,
		nameEng: "Al-Awwal",
		nameHin: "अल अव्वल",
		meaning: "सब से पहले",
	},
	{
		id: 74,
		nameEng: "Al-Akhir",
		nameHin: "अल आखिर",
		meaning: "सब के बाद",
	},
	{
		id: 75,
		nameEng: "Az-Zahir",
		nameHin: "अज ज़ाहिर",
		meaning: "स्पष्ट, ज़ाहिर",
	},
	{
		id: 76,
		nameEng: "Al-Batin",
		nameHin: "अल बातिन",
		meaning: "पोशीदा",
	},
	{
		id: 77,
		nameEng: "Al-Wali",
		nameHin: "अल वाली",
		meaning: "बिगड़ी बनाने वाला",
	},
	{
		id: 78,
		nameEng: "Al-Muta'ali",
		nameHin: "अल मुताआली",
		meaning: "सब से बलंद व बरतर",
	},
	{
		id: 79,
		nameEng: "Al-Barr",
		nameHin: "अल बर",
		meaning: "बड़ा अच्चा सुलूक करने वाला",
	},
	{
		id: 80,
		nameEng: "At-Tawwab",
		nameHin: "अत तव्वाब",
		meaning: "सब से ज्यादा कुबूल करने वाला",
	},
	{
		id: 81,
		nameEng: "Al-Muntaqim",
		nameHin: "अल मुन्ताकिम",
		meaning: "बदला लेने वाला",
	},
	{
		id: 82,
		nameEng: "Al-Afuww",
		nameHin: "अल अफुव्व",
		meaning: "बहुत ज्यादा माफ़ करने वाला",
	},
	{
		id: 83,
		nameEng: "Ar-Rauf",
		nameHin: "अर रऊफ",
		meaning: "बहुत बड़ा मुश्फिक",
	},
	{
		id: 84,
		nameEng: "Malik-ul-Mulk",
		nameHin: "मालिकुल मुल्क",
		meaning: "मुल्कों का मालिक",
	},
	{
		id: 85,
		nameEng: "Dhu-l-Jalali wal-Ikram",
		nameHin: "जुल जलाली वल इकराम",
		meaning: "अजमतो जलाल और इकराम वाला",
	},
	{
		id: 86,
		nameEng: "Al-Muqsit",
		nameHin: "अल मुक्सित",
		meaning: "अदलो इन्साफ कायम करने वाला",
	},
	{
		id: 87,
		nameEng: "Al-Jami'u",
		nameHin: "अल जामिऊ",
		meaning: "सब को जमा करने वाला",
	},
	{
		id: 88,
		nameEng: "Al-Ghani",
		nameHin: "अल गनी",
		meaning: "बड़ा बेनियाज़ व बेपरवा",
	},
	{
		id: 89,
		nameEng: "Al-Mughni",
		nameHin: "अल मुग्नी",
		meaning: "बेनियाज़ व गनी बना देने वाला",
	},
	{
		id: 90,
		nameEng: "Al-Mani'u",
		nameHin: "अल मानिऊ",
		meaning: "देने वाला",
	},
	{
		id: 91,
		nameEng: "Az-Zarr",
		nameHin: "अज ज़ार्र",
		meaning: "नुकसान पहुँचाने वाला",
	},
	{
		id: 92,
		nameEng: "An-Nafi'u",
		nameHin: "अन नाफिऊ",
		meaning: "नफा पहुँचाने वाला",
	},
	{
		id: 93,
		nameEng: "An-Nur",
		nameHin: "अन नूर",
		meaning: "सर से पैर तक नूर बख्शने वाला",
	},
	{
		id: 94,
		nameEng: "Al-Hadi",
		nameHin: "अल हादी",
		meaning: "सीधा रास्ता दिखाने और चलाने वाला",
	},
	{
		id: 95,
		nameEng: "Al-Badi",
		nameHin: "अल बदी",
		meaning: "बेमिसाल चीज़ को इजाद करने वाला",
	},
	{
		id: 96,
		nameEng: "Al-Baqi",
		nameHin: "अल बाकी",
		meaning: "हमेशा रहने वाला",
	},
	{
		id: 97,
		nameEng: "Al-Waris",
		nameHin: "अल वारिस",
		meaning: "सब के बाद मौजूद रहने वाला",
	},
	{
		id: 98,
		nameEng: "Ar-Rashid",
		nameHin: "अर रशीद",
		meaning: "बहुत रहनुमाई करने वाला",
	},
	{
		id: 99,
		nameEng: "As-Sabur",
		nameHin: "अस सबूर",
		meaning: "सब्र वाला",
	},
	{
		id: 100,
		nameEng: "Al-Wahhab",
		nameHin: "अल वह्हाब",
		meaning: "दान वाला",
	},
];
export default AllahName;
