const surahHin = [
	{
		id: 1,
		surahName: "अल-फातिहा",
		meaning: "खुलासा, शुरू करना",
		totalAyahs: 7,
		totalRukus: 1,
	},
	{
		id: 2,
		surahName: "अल-बकराह",
		meaning: "गाय (बकरी)",
		totalAyahs: 286,
		totalRukus: 40,
	},
	{
		id: 3,
		surahName: "आल-ए-इमरान",
		meaning: "इमरान का परिवार",
		totalAyahs: 200,
		totalRukus: 20,
	},
	{
		id: 4,
		surahName: "अन-निसा",
		meaning: "महिलाएं, औरतें",
		totalAyahs: 176,
		totalRukus: 24,
	},
	{
		id: 5,
		surahName: "अल-माइदाह",
		meaning: "बहुत सारा भोजन दस्तरखान",
		totalAyahs: 120,
		totalRukus: 16,
	},
	{
		id: 6,
		surahName: "अल-अनआम",
		meaning: "पशुओं का भाग, जानवर, मवेशी",
		totalAyahs: 165,
		totalRukus: 20,
	},
	{
		id: 7,
		surahName: "अल-अराफ",
		meaning: "ऊंचाई, बुलंदिया,",
		totalAyahs: 206,
		totalRukus: 24,
	},
	{
		id: 8,
		surahName: "अल-अनफाल",
		meaning: "लूट, माले गनीमत",
		totalAyahs: 75,
		totalRukus: 10,
	},
	{
		id: 9,
		surahName: "अत-तौबा",
		meaning: "तोबा, माफी",
		totalAyahs: 129,
		totalRukus: 16,
	},
	{
		id: 10,
		surahName: "यूनुस",
		meaning: "यूनुस (जोना), एक नबी का नाम",
		totalAyahs: 109,
		totalRukus: 11,
	},
	{
		id: 11,
		surahName: "हूद",
		meaning: "हूद, एक नबी का नाम",
		totalAyahs: 123,
		totalRukus: 10,
	},
	{
		id: 12,
		surahName: "यूसुफ",
		meaning: "यूसुफ (यूसुफ), एक नबी का नेम",
		totalAyahs: 111,
		totalRukus: 12,
	},
	{
		id: 13,
		surahName: "अर-राद",
		meaning: "बिजली, बादल की गरज",
		totalAyahs: 43,
		totalRukus: 6,
	},
	{
		id: 14,
		surahName: "इब्राहीम",
		meaning: "इब्राहीम (अब्राम), एक नबी का नाम",
		totalAyahs: 52,
		totalRukus: 7,
	},
	{
		id: 15,
		surahName: "अल-हिज्र",
		meaning: "बंदरगाह, एक जगह का नाम",
		totalAyahs: 99,
		totalRukus: 6,
	},
	{
		id: 16,
		surahName: "अल-नहल",
		meaning: "मधुमक्खी",
		totalAyahs: 128,
		totalRukus: 16,
	},
	{
		id: 17,
		surahName: "अल-इस्राईल, ",
		meaning: "हजरत याक़ूब अलैहिस सलाम की औलाद",
		totalAyahs: 111,
		totalRukus: 12,
	},
	{
		id: 18,
		surahName: "अल-कहफ",
		meaning: "गुफा, गुफा",
		totalAyahs: 110,
		totalRukus: 12,
	},
	{
		id: 19,
		surahName: "मरयम",
		meaning: "मरियम (मरियम), हजरत ईसा अलैहिस सलाम की वालिदा मोहरतमा का नाम",
		totalAyahs: 98,
		totalRukus: 6,
	},
	{
		id: 20,
		surahName: "ताहा",
		meaning: "ताहा, हुरूफे मुक़त्तआत के दो हुरूफ़",
		totalAyahs: 135,
		totalRukus: 8,
	},
	{
		id: 21,
		surahName: "अल-अंबिया",
		meaning: "दूत, अल्लाह के तमाम पैगंबर, नबी की जमा (बहुबचन)",
		totalAyahs: 112,
		totalRukus: 7,
	},
	{
		id: 22,
		surahName: "अल-हज्ज",
		meaning: "हज्ज, जियारत काबा",
		totalAyahs: 78,
		totalRukus: 10,
	},
	{
		id: 23,
		surahName: "अल-मुमिनून",
		meaning: "मोमिन, ईमान वाले लोग",
		totalAyahs: 118,
		totalRukus: 6,
	},
	{
		id: 24,
		surahName: "अन-नूर",
		meaning: "प्रकाश, रोशनी",
		totalAyahs: 64,
		totalRukus: 9,
	},
	{
		id: 25,
		surahName: "अल-फुर्कान",
		meaning: "अंतर, सही और गलत मे फर्क करने वाली चीज",
		totalAyahs: 77,
		totalRukus: 8,
	},
	{
		id: 26,
		surahName: "अश-शुअरा",
		meaning: "कवि, शायर लोग, शायर की जमा (बहुबचन)",
		totalAyahs: 227,
		totalRukus: 11,
	},
	{
		id: 27,
		surahName: "अन-नम्ल",
		meaning: "मकड़ी, च्यूँटी",
		totalAyahs: 93,
		totalRukus: 7,
	},
	{
		id: 28,
		surahName: "अल-कसस",
		meaning: "कहानी, किस्से, सच्चे वाकिआत",
		totalAyahs: 88,
		totalRukus: 9,
	},
	{
		id: 29,
		surahName: "अल-अंकबूत",
		meaning: "मकड़ी",
		totalAyahs: 69,
		totalRukus: 7,
	},
	{
		id: 30,
		surahName: "अर-रूम",
		meaning: "रोमी, एक देश का नाम",
		totalAyahs: 60,
		totalRukus: 6,
	},
	{
		id: 31,
		surahName: "लुक्मान",
		meaning: "लुकमान, अल्लाह के एक नेक बुजुर्ग बंदे का नाम",
		totalAyahs: 34,
		totalRukus: 4,
	},
	{
		id: 32,
		surahName: "अल-सजदह",
		meaning: "सजदे में गिरना, झुकना, सजदा करना",
		totalAyahs: 30,
		totalRukus: 3,
	},
	{
		id: 33,
		surahName: "अल-अहजाब",
		meaning: "जिन्न, लश्कर, जमा, गिरोह",
		totalAyahs: 73,
		totalRukus: 9,
	},
	{
		id: 34,
		surahName: "सबा",
		meaning: "शबा, एक कौम का नाम",
		totalAyahs: 54,
		totalRukus: 6,
	},
	{
		id: 35,
		surahName: "फातिर",
		meaning: "सृष्टि करने वाला, पैदा करने वाला ",
		totalAyahs: 45,
		totalRukus: 5,
	},
	{
		id: 36,
		surahName: "यासीन",
		meaning: "यासीन,",
		totalAyahs: 83,
		totalRukus: 5,
	},
	{
		id: 37,
		surahName: "अल-साफात",
		meaning: "सफ, सफ बंदी करने वाले, लाइन मे खड़े होने वाले ",
		totalAyahs: 182,
		totalRukus: 5,
	},
	{
		id: 38,
		surahName: "साद",
		meaning: "साद",
		totalAyahs: 88,
		totalRukus: 5,
	},
	{
		id: 39,
		surahName: "अज़-ज़ुमर",
		meaning: "ज़ुमर, गिरोह दर गिरोह ",
		totalAyahs: 75,
		totalRukus: 8,
	},
	{
		id: 40,
		surahName: "अल-मोमिन",
		meaning: "ईमान वाला ",
		totalAyahs: 85,
		totalRukus: 6,
	},
	{
		id: 41,
		surahName: "अल- हा मीम",
		meaning: "हामीम ",
		totalAyahs: 54,
		totalRukus: 6,
	},
	{
		id: 42,
		surahName: "अश-शूरा",
		meaning: "शूरा, सलाह, मशवरा",
		totalAyahs: 53,
		totalRukus: 5,
	},
	{
		id: 43,
		surahName: "अज़-ज़ुख़रूफ़",
		meaning: "ज़ुख़रूफ़, सोना(गोल्ड)",
		totalAyahs: 89,
		totalRukus: 7,
	},
	{
		id: 44,
		surahName: "अल-दुखान",
		meaning: "उठने वाले, धुआँ",
		totalAyahs: 59,
		totalRukus: 3,
	},
	{
		id: 45,
		surahName: "जासिया",
		meaning: "घुटनों के बल गिरे हुए",
		totalAyahs: "",
		totalRukus: "",
	},
	{
		id: 46,
		surahName: "अल-अहक़ाफ",
		meaning: "खाई, एक जगह का नाम ",
		totalAyahs: 37,
		totalRukus: 4,
	},
	{
		id: 47,
		surahName: "मुहम्मद",
		meaning: "मुहम्मद (मुहम्मद)",
		totalAyahs: 35,
		totalRukus: 4,
	},
	{
		id: 48,
		surahName: "अल-फतह",
		meaning: "जीत,कामयाबी",
		totalAyahs: 38,
		totalRukus: 4,
	},

	{
		id: 49,
		surahName: "अल-हुजुरात",
		meaning: "कमरे, हुजरे, कमरे",
		totalAyahs: 18,
		totalRukus: 2,
	},
	{
		id: 50,
		surahName: "क़ाफ़",
		meaning: "क़ाफ",
		totalAyahs: 45,
		totalRukus: 1,
	},
	{
		id: 51,
		surahName: "ज़ारियात",
		meaning: "वाहक, धूल उड़ाने वाली हवा ",
		totalAyahs: 60,
		totalRukus: 3,
	},
	{
		id: 52,
		surahName: "अत-तूर",
		meaning: "तूर, एक पहाड़ का नाम ",
		totalAyahs: 49,
		totalRukus: 2,
	},
	{
		id: 53,
		surahName: "अन-नज्म",
		meaning: "नज्म (तारे)",
		totalAyahs: 62,
		totalRukus: 3,
	},
	{
		id: 54,
		surahName: "अल-क़मर",
		meaning: "क़मर (चाँद)",
		totalAyahs: 55,
		totalRukus: 3,
	},
	{
		id: 55,
		surahName: "अर-रहमान",
		meaning: "रहमान, बहुत ज्यादा रहम करने वाला",
		totalAyahs: 78,
		totalRukus: 3,
	},
	{
		id: 56,
		surahName: "अल-वाकियह",
		meaning: "घटना होना, कयामत ",
		totalAyahs: 96,
		totalRukus: 3,
	},
	{
		id: 57,
		surahName: "अल-हदीद",
		meaning: "लोहा",
		totalAyahs: 29,
		totalRukus: 2,
	},
	{
		id: 58,
		surahName: "अल-मुजादिलाह",
		meaning: "विवाद, बहस, इखतेलाफ़, झगड़ा ",
		totalAyahs: 22,
		totalRukus: 2,
	},
	{
		id: 59,
		surahName: "अल-हश्र",
		meaning: "उबार, जमा होना, कयामत के दिन दुबारा जिंदा होकर जमा होना ",
		totalAyahs: 24,
		totalRukus: 2,
	},
	{
		id: 60,
		surahName: "अल-मुमतहनह",
		meaning: "मुमतहन, इम्तेहान लेने वाली ",
		totalAyahs: 13,
		totalRukus: 2,
	},
	{
		id: 61,
		surahName: "अल-सफ",
		meaning: "सफ, लाइन के खड़े होना, सफ बंदी ",
		totalAyahs: 14,
		totalRukus: 2,
	},
	{
		id: 62,
		surahName: "अल-जुमुअह",
		meaning: "इकट्ठा करने वाले, हफ्ते के दिनों मे से एक मुबारक दिन ",
		totalAyahs: 11,
		totalRukus: 2,
	},
	{
		id: 63,
		surahName: "अल-मुनाफिकून",
		meaning: "मुनाफिकून लोग",
		totalAyahs: 11,
		totalRukus: 2,
	},
	{
		id: 64,
		surahName: "अत-तगाबुन",
		meaning: "टागबुन, हार-जीत, नुकसान से गुजरना ",
		totalAyahs: 18,
		totalRukus: 2,
	},
	{
		id: 65,
		surahName: "अत-तलाक",
		meaning: "तलाक, आजाद करना",
		totalAyahs: 24,
		totalRukus: 2,
	},
	{
		id: 66,
		surahName: "अत-तहरीम",
		meaning: "तहरीम, हराम कर देना ",
		totalAyahs: 12,
		totalRukus: 2,
	},
	{
		id: 67,
		surahName: "अल-मुल्क",
		meaning: "राजदानी, बादशाही",
		totalAyahs: 30,
		totalRukus: 2,
	},
	{
		id: 68,
		surahName: "अल-क़लम",
		meaning: "कलम, पेन ",
		totalAyahs: 52,
		totalRukus: 2,
	},
	{
		id: 69,
		surahName: "अल-हाक्काह",
		meaning: "सच, हकीकत, कयामत",
		totalAyahs: 52,
		totalRukus: 2,
	},
	{
		id: 70,
		surahName: "अल-माअरिज",
		meaning: "उठने वाला, बुलंदिया ",
		totalAyahs: 44,
		totalRukus: 2,
	},
	{
		id: 71,
		surahName: "नूह",
		meaning: "नूह, एक नबी का नाम",
		totalAyahs: 28,
		totalRukus: 2,
	},
	{
		id: 72,
		surahName: "अल-जिन",
		meaning: "जिन्न, आग से पैदा की हुई अल्लाह की एक मखलुक ",
		totalAyahs: 28,
		totalRukus: 2,
	},
	{
		id: 73,
		surahName: "अल-मुजम्मिल",
		meaning: "लपेटा हुआ",
		totalAyahs: 20,
		totalRukus: 2,
	},
	{
		id: 74,
		surahName: "अल-मुदस्सिर",
		meaning: "असर पड़ने वाला, चादर ओढ़ने वाला ",
		totalAyahs: 20,
		totalRukus: 2,
	},
	{
		id: 75,
		surahName: "अल-क़ियामाह",
		meaning: "खड़े होना, कयामत, यकीनन कायम होने वाली ",
		totalAyahs: 40,
		totalRukus: 2,
	},
	{
		id: 76,
		surahName: "अल-दहर",
		meaning: "जमाना, अरसा, वक्त",
		totalAyahs: 31,
		totalRukus: 2,
	},
	{
		id: 77,
		surahName: "अल-मुर्सलात",
		meaning: "भेजे गए, हवाएं",
		totalAyahs: 50,
		totalRukus: 2,
	},
	{
		id: 78,
		surahName: "अन-नबा",
		meaning: "समाचार, अहम खबर",
		totalAyahs: 40,
		totalRukus: 2,
	},
	{
		id: 79,
		surahName: "अन-नाज़िअात",
		meaning: "नाजिअात, सख्ती से खीचने वाले",
		totalAyahs: 46,
		totalRukus: 2,
	},
	{
		id: 80,
		surahName: "अबसा",
		meaning: "चेहरा मोड़ना",
		totalAyahs: 42,
		totalRukus: 1,
	},
	{
		id: 81,
		surahName: "अत-तकवीर",
		meaning: "तकवीर, लपेटना",
		totalAyahs: 29,
		totalRukus: 1,
	},
	{
		id: 82,
		surahName: "अल-इन्फितार",
		meaning: "बड़े से बड़ा फटना",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 83,
		surahName: "अल-मुतफ़िफीन",
		meaning: "मुतफ़िफीन, नाप तौल मे कमी करने वाला",
		totalAyahs: 36,
		totalRukus: 1,
	},
	{
		id: 84,
		surahName: "अल-इन्शिकाक",
		meaning: "इन्शिकाक, फट जाना",
		totalAyahs: 25,
		totalRukus: 1,
	},
	{
		id: 85,
		surahName: "अल-बुरुज",
		meaning: "तारे, सितारे का आसमान ",
		totalAyahs: 22,
		totalRukus: 1,
	},
	{
		id: 86,
		surahName: "अत-तारिक",
		meaning: "तारिक (तारे वाला), चमकता तारा",
		totalAyahs: 17,
		totalRukus: 1,
	},
	{
		id: 87,
		surahName: "अल-आला",
		meaning: "सबसे ऊँचा",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 88,
		surahName: "अल-गशियाह",
		meaning: "लचीलापन, छा जाने वाली मुसीबत (कयामत)",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 89,
		surahName: "अल-फ़जर",
		meaning: "सुबह",
		totalAyahs: 30,
		totalRukus: 1,
	},
	{
		id: 90,
		surahName: "अल-बलद",
		meaning: "नगर",
		totalAyahs: 24,
		totalRukus: 1,
	},
	{
		id: 91,
		surahName: "अश-शम्स",
		meaning: "सूरज",
		totalAyahs: 15,
		totalRukus: 1,
	},
	{
		id: 92,
		surahName: "अल-लैल",
		meaning: "रात",
		totalAyahs: 21,
		totalRukus: 1,
	},
	{
		id: 93,
		surahName: "अद-दुहा",
		meaning: "दोपहर, दिन की रोशनी",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 94,
		surahName: "अश-शरह",
		meaning: "खोलना",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 95,
		surahName: "अत-तीन",
		meaning: "फल, अंजीर ",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 96,
		surahName: "अल-अलाक",
		meaning: "अलाक, जमा हुआ खून ",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 97,
		surahName: "अल-क़दर",
		meaning: "ताक़िद, क़दर, इज्जत ",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 98,
		surahName: "अल-बय्यिनाह",
		meaning: "साबित करने वाला",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 99,
		surahName: "अज़-ज़लज़ालाह",
		meaning: "ज़लज़ाला, भूकंप ",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 100,
		surahName: "अल-आदियाह",
		meaning: "आदीयाह, घुड़दौड़ का घोड़ा ",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 101,
		surahName: "अल-क़ारियाह",
		meaning: "खिंचने वाला",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 102,
		surahName: "अत-तकाशूर",
		meaning: "तकाथुर, ज्यादती की ख्वाहिश",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 103,
		surahName: "अल-अस्र",
		meaning: "समय, जमाना",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 104,
		surahName: "अल-हुमजतहनह",
		meaning: "हमजतहनह, ऐब निकालना",
		totalAyahs: 9,
		totalRukus: 1,
	},
	{
		id: 105,
		surahName: "अल-फ़ील",
		meaning: "हाथी",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 106,
		surahName: "क़ुरैश",
		meaning: "क़ुरैश, अरब के एक कबीले का नाम",
		totalAyahs: 4,
		totalRukus: 1,
	},
	{
		id: 107,
		surahName: "अल-माऊन",
		meaning: "माऊन, आम इस्तेमाल की चीजे",
		totalAyahs: 7,
		totalRukus: 1,
	},
	{
		id: 108,
		surahName: "अल-कव्सर",
		meaning: "कव्सर",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 109,
		surahName: "अल-क़ाफिरून",
		meaning: "नास्तिक, काफिर लोग",
		totalAyahs: 6,
		totalRukus: 1,
	},
	{
		id: 110,
		surahName: "अन-नस्र",
		meaning: "मदद",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 111,
		surahName: "अल-लहब",
		meaning: "लाकोर, आग के शोले",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 112,
		surahName: "अल-इखलास",
		meaning: "इखलास, खालिस, वहदानीयत",
		totalAyahs: 4,
		totalRukus: 1,
	},
	{
		id: 113,
		surahName: "अल-फ़लक",
		meaning: "फालक, सुबह",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 114,
		surahName: "अल-नास",
		meaning: "लोग, इंसान, आदमी लोग",
		totalAyahs: 6,
		totalRukus: 1,
	},
];

export default surahHin;
