const surah = [
	{
		id: 1,
		surahName: "Fatehah",
		meaning: "The Opening",
		totalAyahs: 7,
		totalRukus: 1,
	},
	{
		id: 2,
		surahName: "Baqarah",
		meaning: "The Cow",
		totalAyahs: 286,
		totalRukus: 40,
	},
	{
		id: 3,
		surahName: "Aal-e-Imran",
		meaning: "The Family of Imran",
		totalAyahs: 200,
		totalRukus: 20,
	},
	{
		id: 4,
		surahName: "Nisaa",
		meaning: "The Women",
		totalAyahs: 176,
		totalRukus: 24,
	},
	{
		id: 5,
		surahName: "Maidah",
		meaning: "The Table spread with foods",
		totalAyahs: 120,
		totalRukus: 16,
	},
	{
		id: 6,
		surahName: "Al-Anaam",
		meaning: "The Cattle",
		totalAyahs: 165,
		totalRukus: 20,
	},
	{
		id: 7,
		surahName: "Al-Araaf",
		meaning: "The wall with Elevations",
		totalAyahs: 206,
		totalRukus: 24,
	},
	{
		id: 8,
		surahName: "Al-Anfaal",
		meaning: "The Spoils of War",
		totalAyahs: 75,
		totalRukus: 10,
	},
	{
		id: 9,
		surahName: "Tawbah",
		meaning: "The Repentance",
		totalAyahs: 129,
		totalRukus: 16,
	},
	{
		id: 10,
		surahName: "Yunus",
		meaning: "The Prophet [Jonah]",
		totalAyahs: 109,
		totalRukus: 11,
	},
	{
		id: 11,
		surahName: "Hud",
		meaning: "The Prophet Hood",
		totalAyahs: 123,
		totalRukus: 10,
	},
	{
		id: 12,
		surahName: "Yusouf",
		meaning: "The Prophet [Joseph]",
		totalAyahs: 111,
		totalRukus: 12,
	},
	{
		id: 13,
		surahName: "Ar-Ra'ad",
		meaning: "The Thunder",
		totalAyahs: 43,
		totalRukus: 6,
	},
	{
		id: 14,
		surahName: "Ibrahim",
		meaning: "The Prophet [Abraham]",
		totalAyahs: 52,
		totalRukus: 7,
	},
	{
		id: 15,
		surahName: "Hijr",
		meaning: "The Rocky Tract",
		totalAyahs: 99,
		totalRukus: 6,
	},
	{
		id: 16,
		surahName: "Nahl",
		meaning: "The Bee",
		totalAyahs: 128,
		totalRukus: 16,
	},
	{
		id: 17,
		surahName: "Israa",
		meaning: "The Journey by Night",
		totalAyahs: 111,
		totalRukus: 12,
	},
	{
		id: 18,
		surahName: "Al-Kahf",
		meaning: "The Cave",
		totalAyahs: 110,
		totalRukus: 12,
	},
	{
		id: 19,
		surahName: "Maryam",
		meaning: "Mary (Mother of Jesus)",
		totalAyahs: 98,
		totalRukus: 6,
	},
	{
		id: 20,
		surahName: "Taha",
		meaning: "One of the Names of Prophet Muhammad",
		totalAyahs: 135,
		totalRukus: 8,
	},
	{
		id: 21,
		surahName: "Al-Anbiya",
		meaning: "The Prophets",
		totalAyahs: 112,
		totalRukus: 7,
	},
	{
		id: 22,
		surahName: "Al-Hajj",
		meaning: "The Pilgrimage",
		totalAyahs: 78,
		totalRukus: 10,
	},
	{
		id: 23,
		surahName: "Al-Muminun",
		meaning: "The Believers",
		totalAyahs: 118,
		totalRukus: 6,
	},
	{
		id: 24,
		surahName: "Al-Nur",
		meaning: "The Light",
		totalAyahs: 64,
		totalRukus: 9,
	},
	{
		id: 25,
		surahName: "Al-Farqan",
		meaning: "The Criterion",
		totalAyahs: 77,
		totalRukus: 6,
	},
	{
		id: 26,
		surahName: "Ash-Shu'ara",
		meaning: "The Poets",
		totalAyahs: 227,
		totalRukus: 11,
	},
	{
		id: 27,
		surahName: "Al-Naml",
		meaning: "The Ant",
		totalAyahs: 93,
		totalRukus: 7,
	},
	{
		id: 28,
		surahName: "Al-Qasas",
		meaning: "The Narration",
		totalAyahs: 88,
		totalRukus: 9,
	},
	{
		id: 29,
		surahName: "Al-Ankabut",
		meaning: "The Spider",
		totalAyahs: 69,
		totalRukus: 7,
	},
	{
		id: 30,
		surahName: "Al-Rum",
		meaning: "The Romans",
		totalAyahs: 60,
		totalRukus: 6,
	},
	{
		id: 31,
		surahName: "Luqman",
		meaning: "Luqman (A wise Man)",
		totalAyahs: 34,
		totalRukus: 4,
	},
	{
		id: 32,
		surahName: "As-Sajdah",
		meaning: "The Prostration",
		totalAyahs: 30,
		totalRukus: 3,
	},
	{
		id: 33,
		surahName: "Al-Ahzab",
		meaning: "The Confederates",
		totalAyahs: 73,
		totalRukus: 9,
	},
	{
		id: 34,
		surahName: "Al-Saba",
		meaning: "Sheba (The Queen)",
		totalAyahs: 54,
		totalRukus: 6,
	},
	{
		id: 35,
		surahName: "Al-Fatir",
		meaning: "The Originator of Creation",
		totalAyahs: 45,
		totalRukus: 5,
	},
	{
		id: 36,
		surahName: "Ya'sin",
		meaning: "One of the Names of Prophet Muhammad",
		totalAyahs: 83,
		totalRukus: 5,
	},
	{
		id: 37,
		surahName: "As-Saffat",
		meaning: "Those Ranged in Ranks",
		totalAyahs: 182,
		totalRukus: 5,
	},
	{
		id: 38,
		surahName: "Suad",
		meaning: "Arabic Alphabet",
		totalAyahs: 88,
		totalRukus: 5,
	},
	{
		id: 39,
		surahName: "Az-Zamar",
		meaning: "The Groups",
		totalAyahs: 75,
		totalRukus: 8,
	},
	{
		id: 40,
		surahName: "Al-Mumin",
		meaning: "The Forgiver/The Believer",
		totalAyahs: 85,
		totalRukus: 9,
	},
	{
		id: 41,
		surahName: "Hamim Sajdah",
		meaning: "In Detail",
		totalAyahs: 54,
		totalRukus: 6,
	},
	{
		id: 42,
		surahName: "Ash-Shura",
		meaning: "The Consultations",
		totalAyahs: 53,
		totalRukus: 5,
	},
	{
		id: 43,
		surahName: "Al-Aukhruf",
		meaning: "The Gold Adornment",
		totalAyahs: 89,
		totalRukus: 7,
	},
	{
		id: 44,
		surahName: "Al-Dukhan",
		meaning: "The Smoke",
		totalAyahs: 59,
		totalRukus: 3,
	},
	{
		id: 45,
		surahName: "Al-Jathiyah",
		meaning: "The Kneeling",
		totalAyahs: 37,
		totalRukus: 4,
	},
	{
		id: 46,
		surahName: "Al-Ahqaf",
		meaning: "The Curved-Sand Hills",
		totalAyahs: 35,
		totalRukus: 4,
	},
	{
		id: 47,
		surahName: "Muhammad",
		meaning: "The Prophet Muhammad",
		totalAyahs: 38,
		totalRukus: 4,
	},
	{
		id: 48,
		surahName: "Al-Fath",
		meaning: "The Victory",
		totalAyahs: 29,
		totalRukus: 4,
	},
	{
		id: 49,
		surahName: "Al-Hujurat",
		meaning: "The Dwellings",
		totalAyahs: 18,
		totalRukus: 2,
	},
	{
		id: 50,
		surahName: "Q'af",
		meaning: "Arabic Alphabet",
		totalAyahs: 45,
		totalRukus: 3,
	},
	{
		id: 51,
		surahName: "Al-Dhariyat",
		meaning: "The wind that Scatters",
		totalAyahs: 60,
		totalRukus: 3,
	},
	{
		id: 52,
		surahName: "Al-Tur",
		meaning: "The Name of Mountain",
		totalAyahs: 49,
		totalRukus: 2,
	},
	{
		id: 53,
		surahName: "Al-Najm",
		meaning: "The Star",
		totalAyahs: 62,
		totalRukus: 3,
	},
	{
		id: 54,
		surahName: "Al-Qamr",
		meaning: "The Moon",
		totalAyahs: 55,
		totalRukus: 3,
	},
	{
		id: 55,
		surahName: "Ar-Rahman",
		meaning: "The Most Gracious",
		totalAyahs: 78,
		totalRukus: 3,
	},
	{
		id: 56,
		surahName: "Al-Waqiah",
		meaning: "The Event",
		totalAyahs: 96,
		totalRukus: 3,
	},
	{
		id: 57,
		surahName: "Al-Hadid",
		meaning: "Iron",
		totalAyahs: 29,
		totalRukus: 4,
	},
	{
		id: 58,
		surahName: "Al-Mujadila",
		meaning: "The Disputation",
		totalAyahs: 22,
		totalRukus: 3,
	},
	{
		id: 59,
		surahName: "Al-Hashr",
		meaning: "The Gathering",
		totalAyahs: 24,
		totalRukus: 3,
	},
	{
		id: 60,
		surahName: "Al-Mumtahana",
		meaning: "The Woman to be Examined",
		totalAyahs: 13,
		totalRukus: 2,
	},
	{
		id: 61,
		surahName: "As-Saff",
		meaning: "The Row or The Rank",
		totalAyahs: 14,
		totalRukus: 2,
	},
	{
		id: 62,
		surahName: "Al-Jumah",
		meaning: "Friday",
		totalAyahs: 11,
		totalRukus: 2,
	},
	{
		id: 63,
		surahName: "Al-Munafiqun",
		meaning: "The Hypocrites",
		totalAyahs: 11,
		totalRukus: 2,
	},
	{
		id: 64,
		surahName: "Al-Taghabun",
		meaning: "Mutual Loss or Gain",
		totalAyahs: 18,
		totalRukus: 2,
	},
	{
		id: 65,
		surahName: "Al-Talaq",
		meaning: "The Divorce",
		totalAyahs: 12,
		totalRukus: 2,
	},
	{
		id: 66,
		surahName: "Al-Tahrim",
		meaning: "The Prohibition",
		totalAyahs: 12,
		totalRukus: 2,
	},
	{
		id: 67,
		surahName: "Al-Mulk",
		meaning: "Dominion",
		totalAyahs: 30,
		totalRukus: 2,
	},
	{
		id: 68,
		surahName: "Al-Qalam",
		meaning: "The Pen",
		totalAyahs: 52,
		totalRukus: 2,
	},
	{
		id: 69,
		surahName: "Al-Haqqah",
		meaning: "The Inevitable",
		totalAyahs: 52,
		totalRukus: 2,
	},
	{
		id: 70,
		surahName: "Al-Maarij",
		meaning: "The Way of Ascent",
		totalAyahs: 44,
		totalRukus: 2,
	},
	{
		id: 71,
		surahName: "Noah",
		meaning: "The Prophet Noah",
		totalAyahs: 28,
		totalRukus: 2,
	},
	{
		id: 72,
		surahName: "Al-J'nn",
		meaning: "Genie",
		totalAyahs: 28,
		totalRukus: 2,
	},
	{
		id: 73,
		surahName: "Al-Muzammil",
		meaning: "The One wrapped in Garment",
		totalAyahs: 20,
		totalRukus: 2,
	},
	{
		id: 74,
		surahName: "Al-Mudashir",
		meaning: "The One Enveloped",
		totalAyahs: 56,
		totalRukus: 2,
	},
	{
		id: 75,
		surahName: "Al-Qiyamah",
		meaning: "The Resurrection",
		totalAyahs: 40,
		totalRukus: 2,
	},
	{
		id: 76,
		surahName: "Al-Dahr",
		meaning: "The Man",
		totalAyahs: 31,
		totalRukus: 2,
	},
	{
		id: 77,
		surahName: "Al-Mursalat",
		meaning: "Those Sent Forth",
		totalAyahs: 50,
		totalRukus: 2,
	},
	{
		id: 78,
		surahName: "Al-Naba",
		meaning: "The Great News",
		totalAyahs: 40,
		totalRukus: 2,
	},
	{
		id: 79,
		surahName: "Al-Naziat",
		meaning: "Those Who Pull Out",
		totalAyahs: 46,
		totalRukus: 2,
	},
	{
		id: 80,
		surahName: "Abasa",
		meaning: "The Frowned",
		totalAyahs: 42,
		totalRukus: 1,
	},
	{
		id: 81,
		surahName: "Al-Takwir",
		meaning: "Wound Round and Lost its Light",
		totalAyahs: 29,
		totalRukus: 1,
	},
	{
		id: 82,
		surahName: "Al-Infitar",
		meaning: "The Cleaving",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 83,
		surahName: "Al-Mutaffafin",
		meaning: "Those Who Deal in Fraud",
		totalAyahs: 36,
		totalRukus: 1,
	},
	{
		id: 84,
		surahName: "Al-Inshiqaq",
		meaning: "The Splitting Asunder",
		totalAyahs: 25,
		totalRukus: 1,
	},
	{
		id: 85,
		surahName: "Al-Bhruj",
		meaning: "The Big Stars",
		totalAyahs: 22,
		totalRukus: 1,
	},
	{
		id: 86,
		surahName: "Al-Tariq",
		meaning: "The Night-Comer",
		totalAyahs: 17,
		totalRukus: 1,
	},
	{
		id: 87,
		surahName: "Al-A'la",
		meaning: "The Most High",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 88,
		surahName: "Al-Ghashiya",
		meaning: "The Overwhelming",
		totalAyahs: 26,
		totalRukus: 1,
	},
	{
		id: 89,
		surahName: "Al-Fajr",
		meaning: "The Break of the Day/The Dawn",
		totalAyahs: 30,
		totalRukus: 1,
	},
	{
		id: 90,
		surahName: "Al-Balad",
		meaning: "The City",
		totalAyahs: 20,
		totalRukus: 1,
	},
	{
		id: 91,
		surahName: "Ash-Shams",
		meaning: "The Sun",
		totalAyahs: 15,
		totalRukus: 1,
	},
	{
		id: 92,
		surahName: "Al-Lail",
		meaning: "The Night",
		totalAyahs: 21,
		totalRukus: 1,
	},
	{
		id: 93,
		surahName: "Al-Duha",
		meaning: "The Forenoon after Sunrise",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 94,
		surahName: "Al-Inshira",
		meaning: "The Opening Forth",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 95,
		surahName: "Al-T'in",
		meaning: "The Fig",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 96,
		surahName: "Al-Alaq",
		meaning: "The Clot",
		totalAyahs: 19,
		totalRukus: 1,
	},
	{
		id: 97,
		surahName: "Al-Qadr",
		meaning: "The Night of Decree",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 98,
		surahName: "Al-Beyinnah",
		meaning: "The Clear Evidence",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 99,
		surahName: "Al-Zilzal",
		meaning: "The Earthquake",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 100,
		surahName: "Al-Aadiyat",
		meaning: "Those Who Runs",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 101,
		surahName: "Al-Qariah",
		meaning: "The Striking Hour",
		totalAyahs: 11,
		totalRukus: 1,
	},
	{
		id: 102,
		surahName: "Al-Takatur",
		meaning: "The Pilling up of Emulous Desire",
		totalAyahs: 8,
		totalRukus: 1,
	},
	{
		id: 103,
		surahName: "Al-Asr",
		meaning: "The Time",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 104,
		surahName: "Al-Humazah",
		meaning: "The Slanderer",
		totalAyahs: 9,
		totalRukus: 1,
	},
	{
		id: 105,
		surahName: "Al-Fil",
		meaning: "The Elephant",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 106,
		surahName: "Al-Qureysh",
		meaning: "A Famous Arab Tribe",
		totalAyahs: 4,
		totalRukus: 1,
	},
	{
		id: 107,
		surahName: "Alma'un",
		meaning: "The Small Kindnesses",
		totalAyahs: 7,
		totalRukus: 1,
	},
	{
		id: 108,
		surahName: "Al-Kauthar",
		meaning: "A River in Paradise",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 109,
		surahName: "Al-Kafirun",
		meaning: "The Disbelievers",
		totalAyahs: 6,
		totalRukus: 1,
	},
	{
		id: 110,
		surahName: "Al-Nasr",
		meaning: "The Help",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 111,
		surahName: "Al-Lahab",
		meaning: "The Palm Rope",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 112,
		surahName: "Al-Ikhlas",
		meaning: "The Purity",
		totalAyahs: 3,
		totalRukus: 1,
	},
	{
		id: 113,
		surahName: "Al-Falaq",
		meaning: "The Day Break",
		totalAyahs: 5,
		totalRukus: 1,
	},
	{
		id: 114,
		surahName: "Al-Nas",
		meaning: "The People",
		totalAyahs: 6,
		totalRukus: 1,
	},
];
export default surah;